### ISSUE TITLE
Easy-Chat

### ISSUE THREAD

**Issue by GregOnNet** [ng-practice/luenen-18-11-19#1]
### Teamaufgabe

Teilt euch in 2 Gruppen auf.
Plant gemeinsam eine Chat-App, die aus einer Anmeldung und einem Chat-Room besteht.

### Anforderungen

- Zur Anmeldung ist nur ein Benutzername erforderlich.
- Der Benutzername wird im SessionStorage hinterlegt.
- Wenn kein Benutzername im SessionStorage gespeichert ist, wird zur Anmeldeseite umgeleitet.
- Es gibt die Möglichkeit eine Nachricht zu versenden.
- Im ChatRoom werden alle versendeten Nachrichten angezeigt.

**Comment by mmyersDE** [comment]
Hi
